### ISSUE TITLE
布局组件还有点小bug，拖入后没占用高度

### ISSUE THREAD

**Issue by linfree** [sahadev/vue-component-creater-ui#1]
应该是布局组件默认没有内容，所以没有高度，导致无法拖入其他组件到布局组件中。
不过可以在“Inspect Components Structure”中选中，然后编辑一下样式或内容，让它占个高度解决。

**Comment by sahadev** [comment]
> 

你get到技巧了。vcc所集成的组件千变万化，在平面上不一定都有默认高度，例如div。所以通过结构检视调整它们的结构可以达到同样的目的，而这个手段可以说是比较全面的。
