### ISSUE TITLE
【bug】 复选框的复制组件功能无效

### ISSUE THREAD

**Issue by luguicheng** [sahadev/vue-component-creater-ui#10]
![image](https://user-images.githubusercontent.com/50764950/144387224-49576988-d955-4246-bcb7-190c59aedf27.png)

![image](https://user-images.githubusercontent.com/50764950/144387342-0a328583-e56c-4953-a696-1c8b0e5b3a89.png)

**Comment by sahadev** [comment]
已移除本功能
