### ISSUE TITLE
添加echart组件后无法正常显示

### ISSUE THREAD

**Issue by zeng8750** [sahadev/vue-component-creater-ui#12]
自定义echart组件，实现了拖拽生成代码的功能，但是echart内容显示会一闪而过

**Comment by sahadev** [comment]
> 自定义echart组件，实现了拖拽生成代码的功能，但是echart内容显示会一闪而过

加我微信看一下吧：SAHADEV-smile，请备注VCC

**Comment by sahadev** [comment]
VCC已经集成eChart：https://vcc3.surge.sh/，不过这个无法正常显示的问题依然存在，不影响代码的生成
