### ISSUE TITLE
组件中使用指令问题

### ISSUE THREAD

**Issue by 15136721807** [sahadev/vue-component-creater-ui#14]
比如v-for='item in datalist',会在data里自动生成item变量，methods中的方法生成代码是只会保留方法名

**Comment by sahadev** [comment]
> 

v-for的问题是指令识别不够精确导致的，methods中生成的函数确实是只有方法名，具体内容是需要开发者定义的

**Comment by 15136721807** [comment]
> > 
> 
> v-for的问题是指令识别不够精确导致的，methods中生成的函数确实是只有方法名，具体内容是需要开发者定义的

感谢回复，v-for的lc_id是一样的，这导致dom树上有节点不能拖拽
