### ISSUE TITLE
在拖动组件到右边的时候会触发一个打开百度搜索的问题,不知道是不是我的单例

### ISSUE THREAD

**Issue by nageslan** [sahadev/vue-component-creater-ui#18]
1.在拖动组件到右边的时候会触发一个打开百度搜索的问题.
2.在本地运行的程序选中子组件后拖动到右边貌似编辑功能全部失效.经过测试线上的没有这个问题.
![图片](https://user-images.githubusercontent.com/79894501/194769831-0df8932b-2f57-403a-ae22-bc9f9c939b7f.png)

**Comment by sahadev** [comment]
可能和浏览器有关系，没有听其他人报过类似的问题
