### ISSUE TITLE
左侧菜单栏支持不

### ISSUE THREAD

**Issue by GoFireStar** [sahadev/vue-component-creater-ui#2]
左侧菜单栏https://vcc.sahadev.tech/中还未找到

**Comment by sahadev** [comment]
> 

左侧菜单栏？不是很明白什么意思

**Comment by Phoenix-GR** [comment]
就是https://vcc.sahadev.tech/网站里没找到左侧菜单栏的拖拽组件

**Comment by sahadev** [comment]
> 

是说这个里面的侧栏吧？https://element.eleme.cn/#/zh-CN/component/menu，VCC集成了另一种形式，通过mode属性进行切换。

**Comment by sahadev** [comment]
已集成Element的menu组件
