### ISSUE TITLE
全是报v-model 错误

### ISSUE THREAD

**Issue by luocong2016** [sahadev/vue-component-creater-ui#22]
![image](https://github.com/sahadev/vue-component-creater-ui/assets/25705196/08d5823f-8305-492b-ae9d-6aaf6a558e96)

![image](https://github.com/sahadev/vue-component-creater-ui/assets/25705196/e644cec9-d8e2-4eac-818c-04797fb43b05)

**Comment by sahadev** [comment]
已解决
